name: Daily Zones Cleanup

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Remove the zones directory
        run: |
          rm -rf datateam_zones/zones
